import Link from "next/link";
import { ArrowRight, BookOpen, CheckCircle2, Clock3, Languages, ListTodo, Users } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { StatusPill } from "@/components/status-pill";
import { formatRelativeTime } from "@/logic/time/format-relative";
import { adminFirestore } from "@/services/firebase/admin";
import { getLanguageReleaseSummaries } from "@/services/firebase/course-repository";
import { getStaffSession } from "@/services/firebase/session";
import { getContentReportTasks } from "@/services/firebase/task-repository";

export default async function DashboardPage() {
  const [session, releases, tasks, applications] = await Promise.all([
    getStaffSession(), getLanguageReleaseSummaries(), getContentReportTasks(),
    adminFirestore().collection("moderatorApplications").where("status", "==", "submitted").count().get(),
  ]);
  const totals = releases.reduce((sum, release) => ({ courses: sum.courses + release.courseCount, levels: sum.levels + release.levelCount, questions: sum.questions + release.questionCount }), { courses: 0, levels: 0, questions: 0 });
  const openTasks = tasks.filter((task) => task.status !== "resolved");
  const metrics = [[Languages, String(releases.filter((release) => release.activeReleaseId).length), "Languages", `${releases.length} configured`], [BookOpen, totals.courses.toLocaleString(), "Courses", `${totals.levels.toLocaleString()} learning levels`], [CheckCircle2, totals.questions.toLocaleString(), "Questions", "From repository JSON"], [Users, String(applications.data().count), "Applications", "Awaiting review"]] as const;
  const firstName = session?.name.split(/\s+/)[0] ?? "there";
  return <><PageHeader eyebrow="Workspace" title={`Welcome, ${firstName}`} description="Live course health, learner reports, applications, and releases across Varnamala." actions={<Link href="/courses" className="focus-ring inline-flex items-center gap-2 rounded-lg bg-brand px-4 py-2.5 text-sm font-bold text-white hover:bg-brand-dark"><BookOpen className="size-4" />Choose language</Link>} />
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([Icon, value, label, note]) => <article className="card p-5" key={label}><div className="flex items-center justify-between"><Icon className="size-5 text-brand" /><span className="text-[11px] font-semibold text-muted">LIVE</span></div><p className="mt-5 text-3xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-sm font-semibold">{label}</p><p className="mt-1 text-xs text-muted">{note}</p></article>)}</section>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1fr_330px]"><section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-line px-5 py-4"><div><h2 className="text-sm font-bold">Language releases</h2><p className="mt-0.5 text-xs text-muted">Each language ships on its own schedule</p></div><Link href="/releases" className="text-xs font-bold text-brand hover:text-brand-dark">View all</Link></div><div className="overflow-x-auto"><table className="w-full text-left"><thead><tr className="border-b border-line bg-slate-50/70 text-[11px] tracking-wider text-muted uppercase"><th className="px-5 py-3 font-semibold">Language</th><th className="px-4 py-3 font-semibold">Release</th><th className="px-4 py-3 font-semibold">Status</th><th className="px-4 py-3 font-semibold">Updated</th><th className="px-4 py-3" /></tr></thead><tbody>{releases.slice(0, 6).map((language) => <tr key={language.language} className="border-b border-line last:border-0 hover:bg-slate-50/60"><td className="px-5 py-3.5"><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-lg bg-brand-soft text-xs font-bold text-brand">{language.nativeName.slice(0, 1)}</span><span><strong className="block text-sm">{language.name}</strong><span className="text-xs text-muted">{language.courseCount} courses</span></span></div></td><td className="px-4 py-3.5 font-mono text-xs">{language.activeReleaseId ?? "—"}</td><td className="px-4 py-3.5"><StatusPill status={language.status === "active" ? "active" : "review"} /></td><td className="px-4 py-3.5 text-xs text-muted">{formatRelativeTime(language.publishedAt)}</td><td className="px-4 py-3.5"><Link href={`/courses/${language.language}`} aria-label={`Edit ${language.name}`}><ArrowRight className="size-4 text-muted" /></Link></td></tr>)}</tbody></table></div></section>
      <aside className="space-y-5"><section className="card p-5"><div className="flex items-center justify-between"><h2 className="text-sm font-bold">Learner reports</h2><span className="rounded-full bg-coral px-2 py-0.5 text-[11px] font-bold text-white">{openTasks.length}</span></div><div className="mt-4 space-y-4">{openTasks.slice(0, 3).map((task) => <div key={task.id} className="border-b border-line pb-4 last:border-0 last:pb-0"><p className="text-sm font-semibold capitalize">{task.language} · {task.course}</p><p className="mt-1 flex items-center gap-1.5 text-xs text-muted"><Clock3 className="size-3" />{task.reasonLabel} · {formatRelativeTime(task.createdAt)}</p></div>)}{!openTasks.length && <p className="flex items-center gap-2 text-xs text-muted"><ListTodo className="size-4" />No open reports.</p>}</div><Link href="/tasks" className="mt-4 flex items-center gap-2 text-xs font-bold text-brand">Open tasks <ArrowRight className="size-3.5" /></Link></section></aside></div>
  </>;
}
