"use client";

import { useEffect, useMemo, useState } from "react";
import { Check, ChevronRight, CircleAlert, Save } from "lucide-react";
import { editorActions } from "@/store/editor-slice";
import { useAppDispatch, useAppSelector } from "@/store/hooks";
import { validateCourse } from "@/logic/courses/validate-course";
import type { CourseFile } from "@/logic/courses/schemas";

export function CourseEditor({ course, language, baseReleaseId }: { course: CourseFile; language: string; baseReleaseId: string }) {
  const dispatch = useAppDispatch();
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);
  const editor = useAppSelector((state) => state.editor);
  useEffect(() => { dispatch(editorActions.openCourse(course)); }, [course, dispatch]);
  const level = editor.draft?.levels[editor.selectedLevel];
  const question = level?.questions[editor.selectedQuestion];
  const issues = useMemo(() => editor.draft ? validateCourse(editor.draft) : [], [editor.draft]);
  if (!editor.draft || !level || !question) return <div className="card p-8 text-sm text-muted">Loading course content…</div>;
  async function saveDraft(): Promise<void> {
    setSaving(true); setSaveError(null);
    try {
      const response = await fetch("/api/drafts", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ language, baseReleaseId, course: editor.draft }) });
      const data: unknown = await response.json();
      if (!response.ok) throw new Error(typeof data === "object" && data && "error" in data ? String(data.error) : "Could not save draft.");
      dispatch(editorActions.markSaved());
    } catch (error) { setSaveError(error instanceof Error ? error.message : "Could not save draft."); }
    finally { setSaving(false); }
  }

  return <div className="grid min-h-[680px] overflow-hidden rounded-xl border border-line bg-surface shadow-sm xl:grid-cols-[220px_270px_1fr]">
    <aside className="border-b border-line bg-canvas p-3 xl:border-r xl:border-b-0"><p className="px-2 pt-2 pb-3 text-[11px] font-bold tracking-wider text-muted uppercase">Course levels</p><div className="space-y-1">{editor.draft.levels.map((item, index) => <button key={item.level} onClick={() => dispatch(editorActions.selectLevel(index))} className={`focus-ring flex w-full items-center gap-3 rounded-lg px-2.5 py-2.5 text-left ${editor.selectedLevel === index ? "bg-brand-soft text-brand-dark" : "hover:bg-slate-100"}`}><span className={`grid size-7 place-items-center rounded-full text-[11px] font-bold ${editor.selectedLevel === index ? "bg-brand text-white" : "border border-line bg-surface text-muted"}`}>{item.level}</span><span className="min-w-0"><strong className="block truncate text-xs">{item.title}</strong><span className="text-[11px] text-muted">{item.questions.length} questions</span></span></button>)}</div></aside>
    <aside className="border-b border-line p-3 xl:border-r xl:border-b-0"><div className="px-2 pt-2 pb-3"><label className="label" htmlFor="level-title">Level {level.level}</label><input id="level-title" className="field py-2 font-semibold" value={level.title} onChange={(event) => dispatch(editorActions.updateLevelTitle(event.target.value))} /></div><div className="space-y-1">{level.questions.map((item, index) => <button key={`${item.sentence}-${index}`} onClick={() => dispatch(editorActions.selectQuestion(index))} className={`focus-ring flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left ${editor.selectedQuestion === index ? "bg-slate-100" : "hover:bg-slate-50"}`}><span className={`size-2 rounded-full ${item.type === "translate" ? "bg-violet-400" : "bg-sky-400"}`} /><span className="min-w-0 flex-1"><strong className="block text-xs">Question {index + 1}</strong><span className="block truncate text-[11px] text-muted">{item.sentence}</span></span><ChevronRight className="size-3.5 text-slate-400" /></button>)}</div></aside>
    <section className="min-w-0"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-line px-5 py-3"><div className="flex items-center gap-2 text-xs"><span className="font-semibold">Question {editor.selectedQuestion + 1}</span><span className="text-slate-300">/</span><span className="text-muted">{question.type === "translate" ? "Translation" : "Conversation"}</span>{saveError && <span className="text-red-600" role="alert">{saveError}</span>}</div><div className="flex items-center gap-2"><span className={`mr-2 hidden text-xs sm:inline ${editor.dirty ? "text-amber-700" : "text-muted"}`}>{editor.dirty ? "Unsaved changes" : editor.savedAt ? "Saved" : "Loaded from active release"}</span><button onClick={() => void saveDraft()} disabled={saving || !editor.dirty} className="focus-ring inline-flex items-center gap-1.5 rounded-lg bg-ink px-3 py-2 text-xs font-bold text-white hover:bg-slate-800 disabled:opacity-50"><Save className="size-3.5" />{saving ? "Saving…" : "Save draft"}</button></div></div>
      <div className="grid gap-7 p-5 lg:grid-cols-[1fr_250px] lg:p-7"><div className="space-y-6"><div><label className="label" htmlFor="sentence">Sentence shown to learner</label><textarea id="sentence" rows={3} className="field resize-y text-base leading-7" value={question.sentence} onChange={(event) => dispatch(editorActions.updateQuestionSentence(event.target.value))} /><p className="mt-1.5 text-xs text-muted">Romanized target-language sentence. Punctuation is allowed.</p></div><fieldset><legend className="label">Answer options</legend><div className="space-y-2.5">{question.options.map((option, index) => <label key={index} className={`flex items-center gap-3 rounded-lg border p-3 ${question.correctAnswer === option ? "border-brand/40 bg-brand-soft/60" : "border-line"}`}><span className={`grid size-5 shrink-0 place-items-center rounded-full border ${question.correctAnswer === option ? "border-brand bg-brand text-white" : "border-slate-300"}`}>{question.correctAnswer === option && <Check className="size-3" />}</span><input aria-label={`Answer option ${index + 1}`} value={option} onChange={(event) => dispatch(editorActions.updateOption({ index, value: event.target.value }))} className="min-w-0 flex-1 bg-transparent text-sm outline-none" /><span className="text-[10px] font-bold tracking-wider text-muted uppercase">{question.correctAnswer === option ? "Correct" : `Option ${index + 1}`}</span></label>)}</div></fieldset><div className="grid gap-4 sm:grid-cols-2"><div><label className="label">Question type</label><div className="field bg-slate-50 text-muted">{question.type === "translate" ? "Translate" : "Multiple choice"}</div></div><div><label className="label">Prompt</label><div className="field truncate bg-slate-50 text-muted">{question.prompt}</div></div></div></div>
        <aside><div className={`rounded-xl border p-4 ${issues.length ? "border-amber-200 bg-amber-50" : "border-emerald-200 bg-emerald-50"}`}><div className="flex items-center gap-2">{issues.length ? <CircleAlert className="size-4 text-amber-700" /> : <Check className="size-4 text-emerald-700" />}<h3 className="text-xs font-bold">{issues.length ? `${issues.length} checks need attention` : "Validation passing"}</h3></div><p className="mt-2 text-xs leading-5 text-muted">{issues.length ? issues[0]?.message : "Structure, answer options, counts, and duplicates all pass."}</p></div><div className="mt-4 rounded-xl border border-line p-4"><p className="text-xs font-bold">Course summary</p><dl className="mt-3 space-y-2 text-xs"><div className="flex justify-between"><dt className="text-muted">Levels</dt><dd className="font-semibold">{editor.draft.levels.length}</dd></div><div className="flex justify-between"><dt className="text-muted">Questions</dt><dd className="font-semibold">{editor.draft.levels.reduce((sum, item) => sum + item.questions.length, 0)}</dd></div><div className="flex justify-between"><dt className="text-muted">Validation</dt><dd className="font-semibold text-emerald-700">{issues.length ? "Review" : "Passing"}</dd></div></dl><p className="mt-4 border-t border-line pt-3 text-[11px] leading-5 text-muted">Save creates your private language draft. Active learners remain on {baseReleaseId} until an administrator publishes a release.</p></div></aside></div>
    </section>
  </div>;
}
