// Flutter imports:
import 'package:flutter/material.dart';

// Project imports:
import 'package:words625/domain/achievement.dart';

/// Every badge in the app.
///
/// Each entry is tiered — the targets list is its levels — so 57 badges is
/// closer to 250 individual milestones. Every one reads a stat the app actually
/// writes; a badge that can never move is worse than no badge at all.
const List<Achievement> achievementCatalogue = [
  // ---- Learning -----------------------------------------------------------
  Achievement(
    id: 'scholar',
    metric: AchievementMetric.xp,
    group: AchievementGroup.learning,
    title: 'Scholar',
    description: 'Earn XP',
    icon: Icons.auto_stories_rounded,
    color: Color(0xFF42A5F5),
    targets: [100, 500, 2000, 10000, 50000],
  ),
  Achievement(
    id: 'champion',
    metric: AchievementMetric.lessons,
    group: AchievementGroup.learning,
    title: 'Champion',
    description: 'Complete lessons',
    icon: Icons.workspace_premium_rounded,
    color: Color(0xFFAB47BC),
    targets: [10, 50, 100, 250, 500],
  ),
  Achievement(
    id: 'sharpshooter',
    metric: AchievementMetric.perfectLessons,
    group: AchievementGroup.learning,
    title: 'Sharpshooter',
    description: 'Finish lessons with no mistakes',
    icon: Icons.track_changes_rounded,
    color: Color(0xFFEF5350),
    targets: [1, 5, 20, 50, 100],
  ),
  Achievement(
    id: 'sage',
    metric: AchievementMetric.dailyXp,
    group: AchievementGroup.learning,
    title: 'Sage',
    description: 'Earn XP in a single day',
    icon: Icons.psychology_rounded,
    color: Color(0xFF66BB6A),
    targets: [100, 250, 500, 1000, 2000],
  ),
  Achievement(
    id: 'first-steps',
    metric: AchievementMetric.levelsCompleted,
    group: AchievementGroup.learning,
    title: 'First Steps',
    description: 'Clear levels',
    icon: Icons.directions_walk_rounded,
    color: Color(0xFF29B6F6),
    targets: [1, 10, 40, 120, 300],
  ),
  Achievement(
    id: 'flawless-run',
    metric: AchievementMetric.perfectLessons,
    group: AchievementGroup.learning,
    title: 'Flawless',
    description: 'Build a record of perfect lessons',
    icon: Icons.verified_rounded,
    color: Color(0xFF26A69A),
    targets: [3, 15, 40, 90, 200],
  ),
  Achievement(
    id: 'apprentice',
    metric: AchievementMetric.lessons,
    group: AchievementGroup.learning,
    title: 'Apprentice',
    description: 'Get your first lessons behind you',
    icon: Icons.school_rounded,
    color: Color(0xFF7E57C2),
    targets: [1, 3, 5, 8, 15],
  ),
  Achievement(
    id: 'centurion',
    metric: AchievementMetric.lessons,
    group: AchievementGroup.learning,
    title: 'Centurion',
    description: 'Reach a hundred lessons and beyond',
    icon: Icons.military_tech_rounded,
    color: Color(0xFFD4A017),
    targets: [100, 200, 400, 800, 1500],
  ),
  Achievement(
    id: 'xp-hoarder',
    metric: AchievementMetric.xp,
    group: AchievementGroup.learning,
    title: 'Hoarder',
    description: 'Pile up serious XP',
    icon: Icons.savings_rounded,
    color: Color(0xFF8D6E63),
    targets: [25000, 75000, 150000, 300000, 600000],
  ),
  Achievement(
    id: 'deep-diver',
    metric: AchievementMetric.levelsCompleted,
    group: AchievementGroup.learning,
    title: 'Deep Diver',
    description: 'Work through a lot of levels',
    icon: Icons.waves_rounded,
    color: Color(0xFF0288D1),
    targets: [50, 150, 400, 800, 1170],
  ),

  // ---- Consistency --------------------------------------------------------
  Achievement(
    id: 'wildfire',
    metric: AchievementMetric.streak,
    group: AchievementGroup.consistency,
    title: 'Wildfire',
    description: 'Keep a streak going',
    icon: Icons.local_fire_department_rounded,
    color: Color(0xFFFF7043),
    targets: [3, 7, 14, 30, 75, 125, 200, 365],
  ),
  Achievement(
    id: 'regular',
    metric: AchievementMetric.streak,
    group: AchievementGroup.consistency,
    title: 'Regular',
    description: 'Show up for a full week',
    icon: Icons.event_available_rounded,
    color: Color(0xFF43A047),
    targets: [2, 4, 6, 7],
  ),
  Achievement(
    id: 'fortnight',
    metric: AchievementMetric.streak,
    group: AchievementGroup.consistency,
    title: 'Fortnight',
    description: 'Two weeks without missing',
    icon: Icons.calendar_month_rounded,
    color: Color(0xFF5C6BC0),
    targets: [10, 14, 21, 28],
  ),
  Achievement(
    id: 'seasoned',
    metric: AchievementMetric.streak,
    group: AchievementGroup.consistency,
    title: 'Seasoned',
    description: 'A streak measured in months',
    icon: Icons.park_rounded,
    color: Color(0xFF2E7D32),
    targets: [60, 90, 180, 270, 365],
  ),
  Achievement(
    id: 'unbroken',
    metric: AchievementMetric.streak,
    group: AchievementGroup.consistency,
    title: 'Unbroken',
    description: 'A streak most people never reach',
    icon: Icons.shield_rounded,
    color: Color(0xFFB71C1C),
    targets: [400, 500, 730, 1000],
  ),
  Achievement(
    id: 'goal-getter',
    metric: AchievementMetric.dailyGoalsHit,
    group: AchievementGroup.consistency,
    title: 'Goal Getter',
    description: 'Hit your daily goal',
    icon: Icons.flag_circle_rounded,
    color: Color(0xFFFFA000),
    targets: [1, 7, 30, 100, 365],
  ),
  Achievement(
    id: 'day-one',
    metric: AchievementMetric.dailyGoalsHit,
    group: AchievementGroup.consistency,
    title: 'Day One',
    description: 'Make a habit of finishing what you started',
    icon: Icons.wb_twilight_rounded,
    color: Color(0xFFEC407A),
    targets: [3, 10, 25, 60, 150],
  ),
  Achievement(
    id: 'marathoner',
    metric: AchievementMetric.dailyXp,
    group: AchievementGroup.consistency,
    title: 'Marathoner',
    description: 'A single day of serious study',
    icon: Icons.directions_run_rounded,
    color: Color(0xFFF4511E),
    targets: [750, 1500, 3000, 5000],
  ),
  Achievement(
    id: 'early-days',
    metric: AchievementMetric.streak,
    group: AchievementGroup.consistency,
    title: 'Getting Started',
    description: 'Come back a second day',
    icon: Icons.play_circle_rounded,
    color: Color(0xFF00ACC1),
    targets: [1, 2, 3],
  ),
  Achievement(
    id: 'reliable',
    metric: AchievementMetric.lessons,
    group: AchievementGroup.consistency,
    title: 'Reliable',
    description: 'Keep coming back to lessons',
    icon: Icons.repeat_rounded,
    color: Color(0xFF546E7A),
    targets: [25, 75, 150, 350, 700],
  ),

  // ---- Mastery ------------------------------------------------------------
  Achievement(
    id: 'course-clear',
    metric: AchievementMetric.coursesCompleted,
    group: AchievementGroup.mastery,
    title: 'Course Clear',
    description: 'Finish whole courses',
    icon: Icons.done_all_rounded,
    color: Color(0xFF7CB342),
    targets: [1, 3, 8, 15, 30],
  ),
  Achievement(
    id: 'completionist',
    metric: AchievementMetric.coursesCompleted,
    group: AchievementGroup.mastery,
    title: 'Completionist',
    description: 'Finish every course in a language',
    icon: Icons.inventory_rounded,
    color: Color(0xFF00897B),
    targets: [15, 30, 45, 60],
  ),
  Achievement(
    id: 'polyglot',
    metric: AchievementMetric.languages,
    group: AchievementGroup.mastery,
    title: 'Polyglot',
    description: 'Study more than one language',
    icon: Icons.translate_rounded,
    color: Color(0xFF3949AB),
    targets: [2, 3, 5, 8, 13],
  ),
  Achievement(
    id: 'subcontinental',
    metric: AchievementMetric.languages,
    group: AchievementGroup.mastery,
    title: 'Subcontinental',
    description: 'Reach across the whole map',
    icon: Icons.public_rounded,
    color: Color(0xFF00838F),
    targets: [4, 7, 10, 13],
  ),
  Achievement(
    id: 'scribe',
    metric: AchievementMetric.lettersPracticed,
    group: AchievementGroup.mastery,
    title: 'Scribe',
    description: 'Practise letters in the script',
    icon: Icons.draw_rounded,
    color: Color(0xFF6D4C41),
    targets: [10, 50, 150, 400, 1000],
  ),
  Achievement(
    id: 'calligrapher',
    metric: AchievementMetric.lettersPracticed,
    group: AchievementGroup.mastery,
    title: 'Calligrapher',
    description: 'Know the alphabet inside out',
    icon: Icons.brush_rounded,
    color: Color(0xFF4E342E),
    targets: [200, 600, 1500, 3000],
  ),
  Achievement(
    id: 'curious',
    metric: AchievementMetric.wordsTapped,
    group: AchievementGroup.mastery,
    title: 'Curious',
    description: 'Tap words to find out what they mean',
    icon: Icons.touch_app_rounded,
    color: Color(0xFF039BE5),
    targets: [25, 100, 400, 1000, 2500],
  ),
  Achievement(
    id: 'lexicographer',
    metric: AchievementMetric.wordsTapped,
    group: AchievementGroup.mastery,
    title: 'Lexicographer',
    description: 'Look up a small dictionary',
    icon: Icons.menu_book_rounded,
    color: Color(0xFF1565C0),
    targets: [500, 1500, 3000, 6000],
  ),
  Achievement(
    id: 'first-course',
    metric: AchievementMetric.coursesCompleted,
    group: AchievementGroup.mastery,
    title: 'Groundwork',
    description: 'Finish your first course',
    icon: Icons.foundation_rounded,
    color: Color(0xFF8E24AA),
    targets: [1, 2, 4],
  ),
  Achievement(
    id: 'well-read',
    metric: AchievementMetric.levelsCompleted,
    group: AchievementGroup.mastery,
    title: 'Well Read',
    description: 'Levels behind you, across any language',
    icon: Icons.local_library_rounded,
    color: Color(0xFF00695C),
    targets: [90, 270, 540, 1170, 2340],
  ),

  // ---- Games --------------------------------------------------------------
  Achievement(
    id: 'matchmaker',
    metric: AchievementMetric.matchGames,
    group: AchievementGroup.games,
    title: 'Matchmaker',
    description: 'Play Match Madness',
    icon: Icons.grid_view_rounded,
    color: Color(0xFF00BCD4),
    targets: [1, 10, 40, 100, 250],
  ),
  Achievement(
    id: 'high-scorer',
    metric: AchievementMetric.matchBest,
    group: AchievementGroup.games,
    title: 'High Scorer',
    description: 'Set a big Match Madness score',
    icon: Icons.leaderboard_rounded,
    color: Color(0xFFFFB300),
    targets: [200, 500, 1000, 2500, 5000],
  ),
  Achievement(
    id: 'round-runner',
    metric: AchievementMetric.matchRounds,
    group: AchievementGroup.games,
    title: 'Round Runner',
    description: 'Clear rounds against the clock',
    icon: Icons.timer_rounded,
    color: Color(0xFFE64A19),
    targets: [5, 25, 75, 200, 500],
  ),
  Achievement(
    id: 'combo-king',
    metric: AchievementMetric.bestCombo,
    group: AchievementGroup.games,
    title: 'On Fire',
    description: 'Match pairs without a single slip',
    icon: Icons.bolt_rounded,
    color: Color(0xFFFDD835),
    targets: [5, 10, 20, 35, 50],
  ),
  Achievement(
    id: 'quickfire',
    metric: AchievementMetric.matchRounds,
    group: AchievementGroup.games,
    title: 'Quickfire',
    description: 'Get deep into a single run',
    icon: Icons.speed_rounded,
    color: Color(0xFFD81B60),
    targets: [10, 50, 150, 400],
  ),
  Achievement(
    id: 'regular-player',
    metric: AchievementMetric.matchGames,
    group: AchievementGroup.games,
    title: 'Regular Player',
    description: 'Keep coming back to the game',
    icon: Icons.sports_esports_rounded,
    color: Color(0xFF5E35B1),
    targets: [5, 20, 60, 150, 400],
  ),
  Achievement(
    id: 'record-breaker',
    metric: AchievementMetric.matchBest,
    group: AchievementGroup.games,
    title: 'Record Breaker',
    description: 'Push your best score higher',
    icon: Icons.trending_up_rounded,
    color: Color(0xFFF06292),
    targets: [1500, 3000, 6000, 10000],
  ),
  Achievement(
    id: 'unshakeable',
    metric: AchievementMetric.bestCombo,
    group: AchievementGroup.games,
    title: 'Unshakeable',
    description: 'A streak of matches nobody breaks',
    icon: Icons.whatshot_rounded,
    color: Color(0xFFBF360C),
    targets: [25, 40, 60, 80],
  ),

  // ---- Community ----------------------------------------------------------
  Achievement(
    id: 'first-word',
    metric: AchievementMetric.comments,
    group: AchievementGroup.community,
    title: 'Speaks Up',
    description: 'Post in a course discussion',
    icon: Icons.chat_bubble_rounded,
    color: Color(0xFF26C6DA),
    targets: [1, 5, 20, 60, 150],
  ),
  Achievement(
    id: 'explainer',
    metric: AchievementMetric.helpfulVotes,
    group: AchievementGroup.community,
    title: 'Explainer',
    description: 'Get upvotes on what you wrote',
    icon: Icons.lightbulb_rounded,
    color: Color(0xFFFFCA28),
    targets: [1, 10, 50, 150, 500],
  ),
  Achievement(
    id: 'trusted-voice',
    metric: AchievementMetric.helpfulVotes,
    group: AchievementGroup.community,
    title: 'Trusted Voice',
    description: 'Become someone others rely on',
    icon: Icons.verified_user_rounded,
    color: Color(0xFF00796B),
    targets: [100, 300, 750, 2000],
  ),
  Achievement(
    id: 'proofreader',
    metric: AchievementMetric.reports,
    group: AchievementGroup.community,
    title: 'Proofreader',
    description: 'Report mistakes in the course content',
    icon: Icons.fact_check_rounded,
    color: Color(0xFFEF6C00),
    targets: [1, 5, 15, 40],
  ),
  Achievement(
    id: 'quality-control',
    metric: AchievementMetric.reports,
    group: AchievementGroup.community,
    title: 'Quality Control',
    description: 'Keep the courses honest',
    icon: Icons.rule_rounded,
    color: Color(0xFFC62828),
    targets: [10, 30, 75, 150],
  ),
  Achievement(
    id: 'cheerleader',
    metric: AchievementMetric.hiFivesSent,
    group: AchievementGroup.community,
    title: 'Cheerleader',
    description: 'Send hi-fives to other learners',
    icon: Icons.front_hand_rounded,
    color: Color(0xFFFF8A65),
    targets: [1, 10, 50, 200, 500],
  ),
  Achievement(
    id: 'well-liked',
    metric: AchievementMetric.hiFivesReceived,
    group: AchievementGroup.community,
    title: 'Well Liked',
    description: 'Collect hi-fives from other learners',
    icon: Icons.favorite_rounded,
    color: Color(0xFFE91E63),
    targets: [1, 10, 50, 200, 500],
  ),
  Achievement(
    id: 'friendly',
    metric: AchievementMetric.friends,
    group: AchievementGroup.community,
    title: 'Friendly',
    description: 'Follow other learners',
    icon: Icons.people_rounded,
    color: Color(0xFF26C6DA),
    targets: [1, 5, 10, 20, 50],
  ),
  Achievement(
    id: 'conversationalist',
    metric: AchievementMetric.comments,
    group: AchievementGroup.community,
    title: 'Conversationalist',
    description: 'Keep the discussions going',
    icon: Icons.forum_rounded,
    color: Color(0xFF0097A7),
    targets: [25, 75, 200, 500],
  ),
  Achievement(
    id: 'good-company',
    metric: AchievementMetric.hiFivesReceived,
    group: AchievementGroup.community,
    title: 'Good Company',
    description: 'People notice what you are doing',
    icon: Icons.celebration_rounded,
    color: Color(0xFFAD1457),
    targets: [25, 100, 300, 800],
  ),

  // ---- Collection ---------------------------------------------------------
  Achievement(
    id: 'winner',
    metric: AchievementMetric.leagueXp,
    group: AchievementGroup.collection,
    title: 'Winner',
    description: 'Earn XP towards your league',
    icon: Icons.emoji_events_rounded,
    color: Color(0xFFFFA726),
    targets: [500, 2000, 8000, 25000, 75000],
  ),
  Achievement(
    id: 'contender',
    metric: AchievementMetric.leagueXp,
    group: AchievementGroup.collection,
    title: 'Contender',
    description: 'Climb the league table',
    icon: Icons.stacked_line_chart_rounded,
    color: Color(0xFF7B1FA2),
    targets: [1000, 5000, 15000, 40000],
  ),
  Achievement(
    id: 'treasurer',
    metric: AchievementMetric.gems,
    group: AchievementGroup.collection,
    title: 'Treasurer',
    description: 'Collect gems',
    icon: Icons.diamond_rounded,
    color: Color(0xFF00B8D4),
    targets: [50, 250, 1000, 5000, 20000],
  ),
  Achievement(
    id: 'wealthy',
    metric: AchievementMetric.gems,
    group: AchievementGroup.collection,
    title: 'Wealthy',
    description: 'Build up a real reserve',
    icon: Icons.account_balance_rounded,
    color: Color(0xFF283593),
    targets: [2500, 10000, 30000, 100000],
  ),
  Achievement(
    id: 'collector',
    metric: AchievementMetric.badges,
    group: AchievementGroup.collection,
    title: 'Collector',
    description: 'Unlock other badges',
    icon: Icons.badge_rounded,
    color: Color(0xFF6A1B9A),
    targets: [5, 15, 30, 45, 57],
  ),
  Achievement(
    id: 'archivist',
    metric: AchievementMetric.badges,
    group: AchievementGroup.collection,
    title: 'Archivist',
    description: 'Fill the cabinet',
    icon: Icons.inventory_2_rounded,
    color: Color(0xFF37474F),
    targets: [10, 25, 40, 50],
  ),
  Achievement(
    id: 'veteran',
    metric: AchievementMetric.xp,
    group: AchievementGroup.collection,
    title: 'Veteran',
    description: 'Time served, XP earned',
    icon: Icons.star_rounded,
    color: Color(0xFFFFD54F),
    targets: [5000, 20000, 60000, 150000],
  ),
  Achievement(
    id: 'devoted',
    metric: AchievementMetric.levelsCompleted,
    group: AchievementGroup.collection,
    title: 'Devoted',
    description: 'A long record of finished levels',
    icon: Icons.auto_awesome_rounded,
    color: Color(0xFFF9A825),
    targets: [200, 600, 1200, 2400],
  ),
  Achievement(
    id: 'all-rounder',
    metric: AchievementMetric.badges,
    group: AchievementGroup.collection,
    title: 'All-Rounder',
    description: 'Earn badges from every corner of the app',
    icon: Icons.hexagon_rounded,
    color: Color(0xFF00ACC1),
    targets: [20, 35, 50, 57],
  ),
];
