// Project imports:
import 'package:words625/core/enums.dart';

final allLevel1WordsKannada = {
  "I": "Naanu",
  "You": "Neenu",
  "We": "Naavu",
  "This": "Idu",
  "That": "Adu",
  "Here": "Illi",
  "There": "Alli",
  "Yes": "Howdu",
  "No": "Illa",
  "Man": "Ganda",
  "Woman": "Hendathi",
  "Boy": "Huduga",
  "Girl": "Hudugi",
  "Friend": "Sneehita",
  "Love": "Preeti",
  "Happy": "Santosha",
  "Sad": "Dukha",
  "Good": "Ollayadu",
  "Bad": "Kettadu",
  "Come": "Baa",
  "Go": "Hogu",
  "Eat": "Tinnu",
  "Drink": "Kudi",
  "Sleep": "Nidre",
  "Walk": "Nadeyu",
  "Run": "Odu",
  "Stand": "Nilu",
  "Sit": "Koodu",
  "Speak": "Maatanadu",
  "Listen": "Keliri"
};

final allLevel1WordsTamil = {
  "I": "Naan",
  "You": "Neenga / Nee",
  "We": "Naanga / Naam",
  "This": "Idhu",
  "That": "Adhu",
  "Here": "Inge",
  "There": "Ange",
  "Yes": "Aam",
  "No": "Illai",
  "Man": "Aambala",
  "Woman": "Pombala",
  "Boy": "Payyan",
  "Girl": "Ponnu",
  "Friend": "Nanban",
  "Love": "Kaadhal",
  "Happy": "Magizhchi",
  "Sad": "Varutham",
  "Good": "Nalladhu",
  "Bad": "Kettadhu",
  "Come": "Vaa",
  "Go": "Poa",
  "Eat": "Saapidu",
  "Drink": "Kudi",
  "Sleep": "Thoongu",
  "Walk": "Nadakkam",
  "Run": "Odu",
  "Stand": "Nillu",
  "Sit": "Utkaar",
  "Speak": "Pesu",
  "Listen": "Kaelu"
};

final allLevel1WordsTelugu = {
  "I": "Nenu",
  "You": "Meeru / Nuvvu",
  "We": "Manam / Memu",
  "This": "Idi",
  "That": "Adi",
  "Here": "Ikkaḍa",
  "There": "Akkada",
  "Yes": "Avunu",
  "No": "Kadu",
  "Man": "Magadu",
  "Woman": "Aada",
  "Boy": "Abbayi",
  "Girl": "Ammai",
  "Friend": "Sneehitudu",
  "Love": "Prema",
  "Happy": "Santosham",
  "Sad": "Duhkham",
  "Good": "Manchidi",
  "Bad": "Chedda",
  "Come": "Raa",
  "Go": "Vellu",
  "Eat": "Tinu",
  "Drink": "Taagu",
  "Sleep": "Nidra",
  "Walk": "Nadava",
  "Run": "Parigettu",
  "Stand": "Nilabaduta",
  "Sit": "Kurchu",
  "Speak": "Matladu",
  "Listen": "Vinu"
};

final allLevel1WordsMalayalam = {
  "I": "Njan",
  "You": "Nee / Ningal",
  "We": "Njangal / Naam",
  "This": "Ithu",
  "That": "Ath",
  "Here": "Ivide",
  "There": "Avide",
  "Yes": "Athu",
  "No": "Illaa",
  "Man": "Aan",
  "Woman": "Pen",
  "Boy": "Ankuttan",
  "Girl": "Pennkutti",
  "Friend": "Suhritt",
  "Love": "Sneham",
  "Happy": "Sandosham",
  "Sad": "Dukham",
  "Good": "Nannayi",
  "Bad": "Cheetha",
  "Come": "Vaa",
  "Go": "Poka",
  "Eat": "Kazhikuka",
  "Drink": "Kudikkuka",
  "Sleep": "Urakkam",
  "Walk": "Nadakkuka",
  "Run": "Oduka",
  "Stand": "Nilkuka",
  "Sit": "Irrikkuka",
  "Speak": "Samsarikkuka",
  "Listen": "Kelkkuka"
};

final allLevel1WordsHindi = {
  "I": "Main",
  "You": "Tum",
  "We": "Hum",
  "This": "Yeh",
  "That": "Woh",
  "Here": "Yahan",
  "There": "Wahan",
  "Yes": "Haan",
  "No": "Nahin",
  "Man": "Aadmi",
  "Woman": "Aurat",
  "Boy": "Ladka",
  "Girl": "Ladki",
  "Friend": "Dost",
  "Love": "Pyar",
  "Happy": "Khush",
  "Sad": "Dukhi",
  "Good": "Accha",
  "Bad": "Bura",
  "Come": "Aao",
  "Go": "Jao",
  "Eat": "Khao",
  "Drink": "Piyo",
  "Sleep": "So jao",
  "Walk": "Chalo",
  "Run": "Daudo",
  "Stand": "Khade raho",
  "Sit": "Baitho",
  "Speak": "Bolo",
  "Listen": "Suno"
};

final allLevel1WordsBengali = {
  "I": "Ami",
  "You": "Tumi",
  "We": "Amra",
  "This": "Eta",
  "That": "Ota",
  "Here": "Ekhane",
  "There": "Okhane",
  "Yes": "Hyang",
  "No": "Na",
  "Man": "Purush",
  "Woman": "Mohila",
  "Boy": "Chele",
  "Girl": "Meye",
  "Friend": "Bondhu",
  "Love": "Bhalobasha",
  "Happy": "Khushi",
  "Sad": "Dukhkhi",
  "Good": "Bhalo",
  "Bad": "Kharap",
  "Come": "Asho",
  "Go": "Jao",
  "Eat": "Khao",
  "Drink": "Pan koro",
  "Sleep": "Ghumao",
  "Walk": "Hanto",
  "Run": "Doura",
  "Stand": "Dariye thako",
  "Sit": "Bosho",
  "Speak": "Bolo",
  "Listen": "Shono"
};

final allLevel1WordsOdia = {
  "I": "Mu",
  "You": "Tume",
  "We": "Ame",
  "This": "Ehi",
  "That": "Sehi",
  "Here": "Ethare",
  "There": "Sethare",
  "Yes": "Han",
  "No": "Na",
  "Man": "Purusha",
  "Woman": "Mahila",
  "Boy": "Pua",
  "Girl": "Jhia",
  "Friend": "Sang",
  "Love": "Prema",
  "Happy": "Khusi",
  "Sad": "Dukhi",
  "Good": "Bhala",
  "Bad": "Kharapa",
  "Come": "Asa",
  "Go": "Jao",
  "Eat": "Khai",
  "Drink": "Piiba",
  "Sleep": "Soiba",
  "Walk": "Chala",
  "Run": "Dauda",
  "Stand": "Tiha hua",
  "Sit": "Basa",
  "Speak": "Kuha",
  "Listen": "Suna"
};

final allLevel1WordsNepali = {
  "I": "Ma",
  "You": "Timi",
  "We": "Hami",
  "This": "Yo",
  "That": "Tyo",
  "Here": "Yaha",
  "There": "Tyaha",
  "Yes": "Ho",
  "No": "Haina",
  "Man": "Manche",
  "Woman": "Mahila",
  "Boy": "Keta",
  "Girl": "Keti",
  "Friend": "Saathi",
  "Love": "Maya",
  "Happy": "Khushi",
  "Sad": "Dukhi",
  "Good": "Ramro",
  "Bad": "Naramro",
  "Come": "Aau",
  "Go": "Jao",
  "Eat": "Khau",
  "Drink": "Piyu",
  "Sleep": "Sutnu",
  "Walk": "Hidnu",
  "Run": "Kudnu",
  "Stand": "Ubhinu",
  "Sit": "Basnu",
  "Speak": "Bolnu",
  "Listen": "Sunnu"
};

final allLevel1WordsAssamese = {
  "I": "Moi",
  "You": "Tumi",
  "We": "Ami",
  "This": "Ei",
  "That": "Xei",
  "Here": "Iyat",
  "There": "Tat",
  "Yes": "Hoi",
  "No": "Nohoi",
  "Man": "Manuh",
  "Woman": "Tiroti",
  "Boy": "Lora",
  "Girl": "Suwali",
  "Friend": "Bondhu",
  "Love": "Bhalpuwa",
  "Happy": "Xukhi",
  "Sad": "Dukhi",
  "Good": "Bhal",
  "Bad": "Beya",
  "Come": "Aha",
  "Go": "Jua",
  "Eat": "Kha",
  "Drink": "Khua",
  "Sleep": "Xuwa",
  "Walk": "Khoja kadha",
  "Run": "Duranta",
  "Stand": "Thiya houk",
  "Sit": "Bahok",
  "Speak": "Kua",
  "Listen": "Xuna"
};

final wordsMap = {
  TargetLanguage.assamese: allLevel1WordsAssamese,
  TargetLanguage.hindi: allLevel1WordsHindi,
  TargetLanguage.bengali: allLevel1WordsBengali,
  TargetLanguage.odia: allLevel1WordsOdia,
  TargetLanguage.nepali: allLevel1WordsNepali,
  TargetLanguage.kannada: allLevel1WordsKannada,
  TargetLanguage.tamil: allLevel1WordsTamil,
  TargetLanguage.telugu: allLevel1WordsTelugu,
  TargetLanguage.malayalam: allLevel1WordsMalayalam,
};
