#!/usr/bin/env ruby
# frozen_string_literal: true

# Downloads one flat SVG per concept in assets/courses/concepts.json into
# assets/images/vocab/, so the First words course can show a picture instead of
# an English translation.
#
# The art comes from Twemoji rather than being drawn: it is CC-BY 4.0, already
# a consistent set, flat enough to read at 96px in both themes, and every file
# is under a kilobyte. Bundling it also means the pictures look the same on
# every platform, which platform emoji fonts do not.
#
#   ruby tool/fetch_vocab_art.rb          # only what is missing
#   ruby tool/fetch_vocab_art.rb --force  # re-download everything

require 'json'
require 'net/http'
require 'pathname'
require 'uri'

ROOT = Pathname.new(__dir__).parent
CONCEPTS = ROOT / 'assets' / 'courses' / 'concepts.json'
OUT_DIR = ROOT / 'assets' / 'images' / 'vocab'

# Pinned so a re-run produces the files that were reviewed, not whatever the
# emoji set looks like today.
TWEMOJI_VERSION = 'v15.1.0'
BASE = "https://cdn.jsdelivr.net/gh/jdecked/twemoji@#{TWEMOJI_VERSION}/assets/svg"

# concept id => Twemoji codepoint.
#
# Most are the obvious glyph. The ones that are not are commented, because a
# substitute picture is a content decision and has to be visible to whoever
# reviews the course rather than buried in a filename.
CODEPOINTS = {
  # Food and drink.
  'water' => '1f4a7',
  'milk' => '1f95b',
  'tea' => '2615',
  'bread' => '1f35e',
  'rice' => '1f35a',
  'egg' => '1f95a',
  'apple' => '1f34e',
  'banana' => '1f34c',
  'mango' => '1f96d',
  # 'vegetable' is composed rather than downloaded - see COMPOSED below.
  'fish' => '1f41f',
  'food' => '1f37d',

  # People.
  'mother' => '1f469',
  'father' => '1f468',
  'brother' => '1f466', # No sibling glyph exists; a boy and a girl carry it.
  'sister' => '1f467',
  'baby' => '1f476',
  'family' => '1f46a',
  'friend' => '1f91d', # Two hands meeting, the nearest thing to friendship.
  'grandmother' => '1f475',
  'grandfather' => '1f474',
  'doctor' => '1fa7a', # A stethoscope, since the doctor glyph is a ZWJ pair.
  'teacher' => '1f393', # A graduation cap, for the same reason.
  'person' => '1f9d1',

  # Home and things.
  'house' => '1f3e0',
  'door' => '1f6aa',
  'window' => '1fa9f',
  'bed' => '1f6cf',
  'chair' => '1fa91',
  'book' => '1f4d6',
  'key' => '1f511',
  'money' => '1f4b0',
  'phone' => '1f4f1',
  'clothes' => '1f455',
  'lamp' => '1f4a1',
  'clock' => '23f0',

  # The body, and the words that go with it.
  'hand' => '270b',
  'eye' => '1f441',
  'ear' => '1f442',
  'nose' => '1f443',
  'mouth' => '1f444',
  'foot' => '1f9b6',
  'hair' => '1f9b1',
  'heart' => '2764',
  'yes' => '2705',
  'no' => '274c',
  'hello' => '1f44b',
  'thanks' => '1f64f',

  # The world outside.
  'sun' => '2600',
  'moon' => '1f319',
  'star' => '2b50',
  'tree' => '1f333',
  'flower' => '1f338',
  'rain' => '1f327',
  'dog' => '1f415',
  'cat' => '1f408',
  'bird' => '1f426',
  'cow' => '1f404',
  'car' => '1f697',
  'road' => '1f6e3'
}.freeze

# Concepts whose picture is built from several glyphs instead of being one.
#
# A single carrot is a carrot, not "vegetable". The tile only reads as the
# category when it shows a small pile, so this one is assembled from three
# Twemoji sources, each scaled and placed inside one 36x36 viewBox.
#
# [codepoint, scale, dx, dy] - drawn back to front.
COMPOSED = {
  'vegetable' => [
    ['1f966', 0.62, -1.5, 1.0],  # broccoli, back left
    ['1f345', 0.52, 17.0, 2.0],  # tomato, back right
    ['1f955', 0.70, 6.0, 13.0]   # carrot, front centre
  ]
}.freeze

LICENSE = <<~TEXT
  The SVG files in this directory are from Twemoji #{TWEMOJI_VERSION}
  (https://github.com/jdecked/twemoji), Copyright Twitter, Inc and other
  contributors, licensed under CC-BY 4.0:

      https://creativecommons.org/licenses/by/4.0/

  They are regenerated by tool/fetch_vocab_art.rb, which also records why any
  concept uses a substitute glyph.
TEXT

def svg_body(source)
  source.sub(/\A.*?<svg[^>]*>/m, '').sub(%r{</svg>\s*\z}m, '').strip
end

def compose(parts)
  layers = parts.map do |codepoint, scale, dx, dy|
    body = fetch(codepoint)
    raise "could not fetch #{codepoint}" if body.nil?

    "  <g transform=\"translate(#{dx} #{dy}) scale(#{scale})\">\n" \
      "#{svg_body(body)}\n  </g>"
  end
  "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 36 36\">\n" \
    "#{layers.join("\n")}\n</svg>\n"
end

def fetch(codepoint)
  uri = URI("#{BASE}/#{codepoint}.svg")
  response = Net::HTTP.get_response(uri)
  return response.body if response.is_a?(Net::HTTPSuccess)

  warn "  #{codepoint}: HTTP #{response.code}"
  nil
end

def main
  force = ARGV.include?('--force')

  concepts = JSON.parse(CONCEPTS.read)['concepts'].map { |concept| concept['id'] }
  missing_codepoint = concepts - CODEPOINTS.keys - COMPOSED.keys
  orphaned = (CODEPOINTS.keys + COMPOSED.keys) - concepts
  unless missing_codepoint.empty?
    abort "No codepoint for: #{missing_codepoint.join(', ')}"
  end
  warn "Codepoints with no concept: #{orphaned.join(', ')}" unless orphaned.empty?

  OUT_DIR.mkpath
  (OUT_DIR / 'LICENSE').write(LICENSE)

  downloaded = 0
  skipped = 0
  failed = []

  concepts.each do |id|
    target = OUT_DIR / "#{id}.svg"
    if target.exist? && !force
      skipped += 1
      next
    end

    body =
      if COMPOSED.key?(id)
        begin
          compose(COMPOSED.fetch(id))
        rescue RuntimeError
          nil
        end
      else
        fetch(CODEPOINTS.fetch(id))
      end

    if body.nil?
      failed << id
      next
    end

    target.write(body)
    downloaded += 1
  end

  puts "#{downloaded} downloaded, #{skipped} already present, #{failed.size} failed"
  abort "Failed: #{failed.join(', ')}" unless failed.empty?
end

main if $PROGRAM_NAME == __FILE__
